### ISSUE TITLE
Le démon ne démarre pas

### ISSUE THREAD

**Issue by Lheriss** [Paul-DS/jeedom-plugin-dahuavto#1]
Test avec portier VTO 2202F. Malheureusement, impossible de démarrer le démon. Voici les logs :

File « /var/www/html/plugins/dahuavto/resources/dahuavto/daemon.py », line 55
logging.error(f"Connection failed will try to connect in 30 seconds ({e}")
^
SyntaxError: invalid syntax
File « /var/www/html/plugins/dahuavto/resources/dahuavto/daemon.py », line 55
logging.error(f"Connection failed will try to connect in 30 seconds ({e}")
^

**Comment by Paul-DS** [comment]
Problème traité ici: https://community.jeedom.com/t/plugin-tiers-sujet-principal-plugin-dahua-vto/56841
